/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sales;

import java.awt.HeadlessException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author cmeehan
 */
public class existingCustomerDataPreviousQuotes extends javax.swing.JFrame {

    /**
     * Creates new form DBSearch
     */
    public existingCustomerDataPreviousQuotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerQuotesTable = new javax.swing.JTable();
        viewSelectedQuoteButton = new javax.swing.JButton();
        exportTableToExcel = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Title");
        title.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        customerQuotesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(customerQuotesTable);

        viewSelectedQuoteButton.setText("View Selected Quote");
        viewSelectedQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSelectedQuoteButtonActionPerformed(evt);
            }
        });

        exportTableToExcel.setText("Export to Excel");
        exportTableToExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportTableToExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewSelectedQuoteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportTableToExcel))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSelectedQuoteButton)
                    .addComponent(exportTableToExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewSelectedQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSelectedQuoteButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = existingCustomerDataPreviousQuotes.customerQuotesTable.getSelectedRow();
        String selectedRowID = customerQuotesTable.getValueAt(selectedRow, 0).toString();
        MainMenu.updateQuoteInformation(selectedRowID);
        this.dispose();
        MainMenu.customerInformationPanel.setVisible(false);
        MainMenu.userInformationPanel.setVisible(false);
        MainMenu.newQuotePanel.setVisible(false);
        MainMenu.updateEditQuotePanel.setVisible(true);
        MainMenu.publishingCenterPanel.setVisible(false);
        MainMenu.searchPanel.setVisible(false);


    }//GEN-LAST:event_viewSelectedQuoteButtonActionPerformed

    private void exportTableToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportTableToExcelActionPerformed
        /**
         * Exports the customer's previous quotes to an excel document saved to
         * the user's desktop
         */
        String userHome = System.getProperty("user.home");

        String queryTitle = title.getText();
        String file = userHome + "\\Desktop\\ " + queryTitle + ".xls";
        try {
            Workbook wb = new HSSFWorkbook(); // Excel workbook
            Sheet sheet = wb.createSheet(); // Worksheet
            org.apache.poi.ss.usermodel.Row row = sheet.createRow(2); // Row created at line 3
            TableModel model = customerQuotesTable.getModel();

            Row headerRow = sheet.createRow(0); // Create row at line 0
            for (int headings = 0; headings < model.getColumnCount(); headings++) {
                headerRow.createCell(headings).setCellValue(model.getColumnName(headings));
            }
            for (int rows = 0; rows < model.getRowCount(); rows++) { // For each table row
                for (int cols = 0; cols < model.getColumnCount(); cols++) { // For each table column
                    row.createCell(cols).setCellValue(model.getValueAt(rows, cols).toString()); //Write value
                }
                // Set the row to the next one in the sequence
                row = sheet.createRow(rows + 3);
            }
            wb.write(new FileOutputStream(file));//Save the file
            JOptionPane.showMessageDialog(null, "The reults have been saved to your desktop");
        } catch (IOException | HeadlessException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_exportTableToExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(existingCustomerDataPreviousQuotes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new existingCustomerDataPreviousQuotes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable customerQuotesTable;
    private javax.swing.JButton exportTableToExcel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel title;
    private javax.swing.JButton viewSelectedQuoteButton;
    // End of variables declaration//GEN-END:variables
}
