package Sales;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cmeehan
 */
import Connections.DBConnection;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.Arrays;

public class newCustomerQuickAddForm extends javax.swing.JDialog {

    public newCustomerQuickAddForm() {
        initComponents();
        setIcon();

    }

    protected int tf;

    public newCustomerQuickAddForm(int tf) {
        this.tf = tf;
    }

    /**
     * Creates new form logIn
     *
     * @param parent
     * @param modal
     */
    public newCustomerQuickAddForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(this);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        companyNameLabel = new javax.swing.JLabel();
        companyNameTextField = new javax.swing.JTextField();
        dbaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        contactFirstnameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contactLastnameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        submitNewCustomerButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        otiNumberTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log-In \"K\" Line RORO Quoting");
        setIconImage(null);
        setIconImages(null);

        companyNameLabel.setText("Company:");

        jLabel3.setText("DBA:");

        jLabel4.setText("First Name:");

        jLabel5.setText("Last Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("New Customer Quick Add");

        submitNewCustomerButton.setText("Save");
        submitNewCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitNewCustomerButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("OTI #:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(companyNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(submitNewCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otiNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactLastnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(contactFirstnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(dbaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(companyNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {companyNameTextField, contactFirstnameTextField, contactLastnameTextField, dbaTextField, otiNumberTextField, submitNewCustomerButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {companyNameLabel, jLabel3, jLabel4, jLabel5, jLabel7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(companyNameLabel)
                    .addComponent(companyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(dbaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(contactFirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(contactLastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel7)
                            .addComponent(otiNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitNewCustomerButton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitNewCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNewCustomerButtonActionPerformed
        /**
         * Adds new customer to the DB
         */

        // Declare all variables;
        String company, dba, firstName, lastName, otiNumber, validateSql, insertSql;
        int lastKey;

        // Connect to the database
        Connection conn = new DBConnection().connect();

        //Get the values from the inputs and assign values to strings
        company = companyNameTextField.getText();
        dba = dbaTextField.getText();
        firstName = contactFirstnameTextField.getText();
        lastName = contactLastnameTextField.getText();
        otiNumber = otiNumberTextField.getText();

        //Form validation
        //Check to make sure at least the company name is input
        if (company.equals("") || company == null) { //if the company name is invalid return an error
            JOptionPane.showMessageDialog(null, "You must enter a company name before you can submit the entry");
            companyNameLabel.setText("Company:*");
            companyNameLabel.setForeground(Color.RED);
        } else { //Check if the company already exists. If it does then return an error. If not then insert into the database. 
            validateSql = "SELECT * FROM rorocustomers WHERE company=? OR dba=?";
            try {
                PreparedStatement validatePS = conn.prepareStatement(validateSql);
                validatePS.setString(1, company);
                validatePS.setString(2, company);
                ResultSet validateResult = validatePS.executeQuery();
                if (validateResult.next()) {
                    JOptionPane.showMessageDialog(null, "This customer already exists");
                } else {
                    insertSql = "INSERT INTO rorocustomers (company, dba, firstname, lastname, oti) VALUES(?,?,?,?,?)";
                    try {
                        PreparedStatement insertPS = conn.prepareStatement(insertSql, Statement.RETURN_GENERATED_KEYS);
                        insertPS.setString(1, company);
                        insertPS.setString(2, dba);
                        insertPS.setString(3, firstName);
                        insertPS.setString(4, lastName);
                        insertPS.setString(5, otiNumber);

                        // Execute the update
                        insertPS.executeUpdate();

                        //Get the auto-generated ID
                        ResultSet keys = insertPS.getGeneratedKeys();
                        lastKey = 1;
                        while (keys.next()) {
                            lastKey = keys.getInt(1);
                        }
                        
                        //Close the connection when finished
                        insertPS.closeOnCompletion();
                                
                        JOptionPane.showMessageDialog(null, company + " has been successfully uploaded to the database. ID: " + lastKey);
                    } catch (SQLException | HeadlessException ex) {
                        JOptionPane.showMessageDialog(null, "Error! Contact your system administrator for assistance");
                        System.out.println(ex.getMessage() + "\n" + Arrays.toString(ex.getStackTrace()));
                    }
                    this.dispose();
                }
            } catch (SQLException | HeadlessException ex) {
                JOptionPane.showMessageDialog(null, "Error! Contact your system administrator for assistance");
                System.out.println(ex.getMessage() + "\n" + Arrays.toString(ex.getStackTrace()));
            }
        }


    }//GEN-LAST:event_submitNewCustomerButtonActionPerformed

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newCustomerQuickAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            newCustomerQuickAddForm dialog = new newCustomerQuickAddForm(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JTextField companyNameTextField;
    private javax.swing.JTextField contactFirstnameTextField;
    private javax.swing.JTextField contactLastnameTextField;
    private javax.swing.JTextField dbaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField otiNumberTextField;
    private javax.swing.JButton submitNewCustomerButton;
    // End of variables declaration//GEN-END:variables

}
