package CustomerService;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cmeehan
 */
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import Connections.DBConnection;
import RORO.*;

public class csExistingCustomer extends javax.swing.JDialog {

    public csExistingCustomer() {
        initComponents();
        setIcon();

    }

    protected int tf;

    public csExistingCustomer(int tf) {
        this.tf = tf;
    }

    /**
     * Creates new form logIn
     *
     * @param parent
     * @param modal
     */
    public csExistingCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(this);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        csExistingCustomerTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cancelCustomerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log-In \"K\" Line RORO Quoting");
        setIconImage(null);
        setIconImages(null);

        csExistingCustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Company Name", "Contact Name", "DBA/Affiliates"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        csExistingCustomerTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(csExistingCustomerTable);

        jLabel1.setText("Customers");

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cancelCustomerButton.setText("Cancel");
        cancelCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelCustomerButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cancelCustomerButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /**
         * Get the information from the selected line and fill in the csCustomer Panel information
         */
        
        // Get the ID from the selected line
        int selectedRow = csExistingCustomerTable.getSelectedRow();
        String selectedID = String.valueOf(csExistingCustomerTable.getValueAt(selectedRow, 0));
        
        //Establish DBConnection
        Connection conn = new DBConnection().connect();
        
        String SQL = "SELECT * FROM rorocustomers WHERE ID=?";
        try{
            PreparedStatement ps = conn.prepareStatement(SQL);
            ps.setString(1, selectedID);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                String ID = rs.getString("ID");
                String firstname = rs.getString("firstname");
                String lastname = rs.getString("lastname");
                String officephone = rs.getString("officephone");
                String mobilephone = rs.getString("mobilephone");
                String  email = rs.getString("email");
                String  title = rs.getString("title");
                String  contact_office_address = rs.getString("contact_office_address");
                String  contact_office_address2 = rs.getString("contact_office_address2");
                String  contact_office_city = rs.getString("contact_office_city");
                String  contact_office_state = rs.getString("contact_office_state");
                String  contact_office_zip_code = rs.getString("contact_office_zip_code");
                String  contact_office_country = rs.getString("contact_office_country");
                String  company = rs.getString("company");
                String  dba = rs.getString("dba");
                String  oti = rs.getString("oti");
                Boolean  freight_forwarder = rs.getBoolean("freight_forwarder");
                Boolean  NVOCC = rs.getBoolean("NVOCC");
                Boolean  BCO = rs.getBoolean("BCO");
                Boolean  Other = rs.getBoolean("Other");
                String  mainphone = rs.getString("mainphone");
                String  secondaryphone = rs.getString("secondaryphone");
                String  fax = rs.getString("fax");
                String  address1 = rs.getString("address1");
                String  address2 = rs.getString("address2");
                String  city = rs.getString("city");
                String  state = rs.getString("state");
                String  zip = rs.getString("zip");
                String  country = rs.getString("country");
                Boolean  contract = rs.getBoolean("contract");
                String  contractnumber = rs.getString("contractnumber");
                String  contractExpiration = rs.getString("contractExpiration");
                String  comments = rs.getString("comments");
                String  mainemail = rs.getString("mainemail");
                
                
                CustomerService.firstNameLabel.setText(firstname);
                CustomerService.lastnameLabel.setText(lastname);
                CustomerService.officePhoneLabel.setText(officephone);
                CustomerService.mobilePhoneLabel.setText(mobilephone);
                CustomerService.contactEmailLabel.setText(email);
                CustomerService.titleLabel.setText(title);
                CustomerService.contactOfficeAddressLabel.setText(contact_office_address);
                CustomerService.contactAddress2Label.setText(contact_office_address2);
                CustomerService.contactCityLabel.setText(contact_office_city);
                CustomerService.contactStateLabel.setText(contact_office_state);
                CustomerService.contactZipLabel.setText(contact_office_zip_code);
                CustomerService.contactCountryLabel.setText(contact_office_country);
                CustomerService.companyIDLabel.setText(ID);
                CustomerService.companyNameLabel.setText(company);
                CustomerService.dbaLabel.setText(dba);
                if(oti.equals("") || oti.equals("null") || oti == null){
                    CustomerService.otiNumberLabel.setText("N/A");
                    CustomerService.otiTypeLabel.setText("N/A");
                }else{
                    CustomerService.otiNumberLabel.setText(oti);
                    if(freight_forwarder == true){
                        CustomerService.otiTypeLabel.setText("Freight Forwarder");
                    }else if(NVOCC == true){
                        CustomerService.otiTypeLabel.setText("NVOCC");
                    }else if(BCO == true){
                        CustomerService.otiTypeLabel.setText("BCO");
                    }else{
                        CustomerService.otiTypeLabel.setText("Other");
                    }
                }
                if(contract == true){
                    CustomerService.scNumberLabel.setText(contractnumber);
                    CustomerService.scExpirationLabel.setText(contractExpiration);
                }else{
                    CustomerService.scNumberLabel.setText("N/A");
                    CustomerService.scExpirationLabel.setText("N/A");
                }
                CustomerService.mainPhoneLabel.setText(mainphone);
                CustomerService.secondaryPhoneLabel.setText(secondaryphone);
                CustomerService.faxNumberLabel.setText(fax);
                CustomerService.webpageLabel.setText(mainemail);
                CustomerService.address1Label.setText(address1);
                CustomerService.address2Label.setText(address2);
                CustomerService.cityLabel.setText(city);
                CustomerService.stateLabel.setText(state);
                CustomerService.zipLabel.setText(zip);
                CustomerService.countryLabel.setText(country);
                CustomerService.commentsTextArea.setText(comments);
                
                this.dispose();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error!\n"+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCustomerButtonActionPerformed
        // TODO add your handling code here:

        MainMenu.existingCompanyIDTextField.setText("");
        MainMenu.existingCompanyNameTextField.setText("");
        this.dispose();
    }//GEN-LAST:event_cancelCustomerButtonActionPerformed

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(csExistingCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            csExistingCustomer dialog = new csExistingCustomer(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelCustomerButton;
    public static javax.swing.JTable csExistingCustomerTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
