/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RORO;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author cmeehan
 */
public class AdminViewQuote extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewQuote
     */
    public AdminViewQuote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        ViewQuotePanel = new javax.swing.JPanel();
        updateThcAttachedCheckBox = new javax.swing.JCheckBox();
        updateWfgAttachedCheckBox = new javax.swing.JCheckBox();
        updateEditQuoteCustomerNameLabel1 = new javax.swing.JLabel();
        updateEditQuoteCustomerNameLabel2 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        lastUpdatedByLabel = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        authorLabel1 = new javax.swing.JLabel();
        updateOFTTextField = new javax.swing.JTextField();
        jLabel124 = new javax.swing.JLabel();
        updateBAFTextField = new javax.swing.JTextField();
        currentAlphaNumeralLabel = new javax.swing.JLabel();
        updateEcaBafTextField = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        updateTHCTextField = new javax.swing.JTextField();
        updateWfgTextField = new javax.swing.JTextField();
        updateOftUnitComboBox = new javax.swing.JComboBox();
        updateBafIncludedCheckBox = new javax.swing.JCheckBox();
        updateDocumentationFeeComboBox = new javax.swing.JComboBox();
        updateDocFeeIncludedCheckBox = new javax.swing.JCheckBox();
        updateEcaComboBox = new javax.swing.JComboBox();
        updateThcComboBox = new javax.swing.JComboBox();
        updateWfgComboBox = new javax.swing.JComboBox();
        updateEcaIncludedCheckBox = new javax.swing.JCheckBox();
        updateThcIncludedCheckBox = new javax.swing.JCheckBox();
        updateWfgIncludedCheckBox = new javax.swing.JCheckBox();
        updateAlphaNumeralTextField = new javax.swing.JTextField();
        updateTradeLane = new javax.swing.JComboBox();
        authorLabel2 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        updateQuoteAccessoriesCheckBox = new javax.swing.JCheckBox();
        jScrollPane12 = new javax.swing.JScrollPane();
        updateEditPackingListTable = new javax.swing.JTable();
        jLabel54 = new javax.swing.JLabel();
        updateQuoteMAFIMinimumCheckBox = new javax.swing.JCheckBox();
        updateEditMAFIMinimumTextField = new javax.swing.JTextField();
        updateContractRateCheckBox = new javax.swing.JCheckBox();
        updateDeclineComboBox = new javax.swing.JComboBox();
        updateTshp2TextField = new javax.swing.JTextField();
        updateWarRiskCheckBox = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        updateCommentsTextArea = new javax.swing.JTextArea();
        updateSpotRateCheckBox = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        updateBookedCheckBox = new javax.swing.JCheckBox();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel59 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel60 = new javax.swing.JLabel();
        updateQuoteIDTextArea = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        updatePOLTextField = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel61 = new javax.swing.JLabel();
        updateEditQuoteCustomerNameLabel3 = new javax.swing.JLabel();
        updatePODTextField = new javax.swing.JTextField();
        editCustomerButton = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        quoteFeedbackCheckBox = new javax.swing.JCheckBox();
        quoteFeedbackComboBox = new javax.swing.JComboBox();
        quoteFeedbackTextField = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        updateQuoteIDSearchButton = new javax.swing.JButton();
        updateDeclineCheckBox = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        updateEditQuoteCustomerNameLabel = new javax.swing.JLabel();
        updateTshp1TextField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel63 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        updateCommodityClassComboBox = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        updateCommodityDescriptionTextField = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        updateHandlingInstructionsComboBox = new javax.swing.JComboBox();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        updateThcAttachedCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateThcAttachedCheckBox.setText("Attached to Email");

        updateWfgAttachedCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateWfgAttachedCheckBox.setText("Attached to Email");

        updateEditQuoteCustomerNameLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updateEditQuoteCustomerNameLabel1.setText("Author:");

        updateEditQuoteCustomerNameLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updateEditQuoteCustomerNameLabel2.setText("Last Updated By:");

        jLabel69.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel69.setText("THC");

        authorLabel.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        authorLabel.setText("N/A");

        jLabel70.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel70.setText("WFG");

        lastUpdatedByLabel.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lastUpdatedByLabel.setText("N/A");

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel71.setText("Documentation Fee");

        authorLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        authorLabel1.setText("|");

        updateOFTTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel124.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel124.setText("Current Alpha Numeral:");

        currentAlphaNumeralLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        currentAlphaNumeralLabel.setText("N/A");

        updateEcaBafTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel129.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel129.setText("Updated Alpha Numeral:");

        updateTHCTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        updateWfgTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        updateOftUnitComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateOftUnitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "W/M", "Unit", "CBM", "Short Ton", "Metric Ton", "MAFI", "per 40 cubic ft", "FAS", "Subject to local charges" }));

        updateBafIncludedCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateBafIncludedCheckBox.setText("Included");

        updateDocumentationFeeComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateDocumentationFeeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "$25 per B/L", "$50 per B/L", "$75 per B/L", " " }));

        updateDocFeeIncludedCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateDocFeeIncludedCheckBox.setText("Included");

        updateEcaComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateEcaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "W/M", "Unit", "CBM", "Short Ton", "Metric Ton", "MAFI", "per 40 cubic ft", "FAS", "Subject to local charges" }));

        updateThcComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateThcComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "W/M", "Unit", "CBM", "Short Ton", "Metric Ton", "MAFI", "per 40 cubic ft", "FAS", "Subject to local charges" }));

        updateWfgComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateWfgComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "W/M", "Unit", "CBM", "Short Ton", "Metric Ton", "MAFI", "per 40 cubic ft", "FAS", "Subject to local charges" }));

        updateEcaIncludedCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateEcaIncludedCheckBox.setText("Included");

        updateThcIncludedCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateThcIncludedCheckBox.setText("Included");

        updateWfgIncludedCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateWfgIncludedCheckBox.setText("Included");

        updateAlphaNumeralTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        updateTradeLane.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateTradeLane.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Trans-Atlantic EB", "Trans-Atlantic WB", "North Atlantic Shuttle EB", "North Atlantic Shuttle WB", "NAX EB", "NAX WB", "ECAMS NB", "ECAMS SB", "Foreign to Foreign" }));

        authorLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        authorLabel2.setText("|");

        jLabel76.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel76.setText("Tshp2");

        updateQuoteAccessoriesCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updateQuoteAccessoriesCheckBox.setText("Accessories");

        updateEditPackingListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Commodity", "Qty", "L(cm)", "W(cm)", "H(cm)", "CBM", "Kgs", "Lbs", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane12.setViewportView(updateEditPackingListTable);

        jLabel54.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Packing List");
        jLabel54.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        updateQuoteMAFIMinimumCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updateQuoteMAFIMinimumCheckBox.setText("MAFI Minimum: $");

        updateEditMAFIMinimumTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        updateContractRateCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updateContractRateCheckBox.setText("Contract Rate");

        updateDeclineComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateDeclineComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "No Service", "Operational Restrictions", "Other (See Comments)" }));

        updateTshp2TextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        updateWarRiskCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updateWarRiskCheckBox.setText("War Risk");

        updateCommentsTextArea.setColumns(15);
        updateCommentsTextArea.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateCommentsTextArea.setRows(5);
        updateCommentsTextArea.setLineWrap(true);
        jScrollPane5.setViewportView(updateCommentsTextArea);

        updateSpotRateCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updateSpotRateCheckBox.setText("Spot Rate");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Update/Edit Quote");
        jLabel21.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        updateBookedCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updateBookedCheckBox.setText("Booked");

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel59.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel59.setText("Trade Lane");

        jLabel78.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel78.setText("Quote ID:");

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel60.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel60.setText("POL");

        updateQuoteIDTextArea.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        updatePOLTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel61.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel61.setText("POD");

        updateEditQuoteCustomerNameLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updateEditQuoteCustomerNameLabel3.setText("Customer Name:");

        updatePODTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        editCustomerButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        editCustomerButton.setText("Edit");
        editCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerButtonActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel62.setText("Tshp1");

        quoteFeedbackCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        quoteFeedbackCheckBox.setText("Feedback");

        quoteFeedbackComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Rate Not Competitive", "Scheduling", "Moved with Other Carrier", "No Feedback From Owner", "Other" }));

        quoteFeedbackTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        updateQuoteIDSearchButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateQuoteIDSearchButton.setText("Search");
        updateQuoteIDSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateQuoteIDSearchButtonActionPerformed(evt);
            }
        });

        updateDeclineCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updateDeclineCheckBox.setText("Decline");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Comments");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        updateEditQuoteCustomerNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateEditQuoteCustomerNameLabel.setText("N/A");

        updateTshp1TextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel63.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel63.setText("Commodity Class");

        jLabel16.setText("$");

        updateCommodityClassComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateCommodityClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Automobile/POV", "Automobile/POV (up to 14 cubic meters)", "Automobile/POV (14 - 17 cubic meters)", "Automobile/POV (17 - 25 cubic meters)", "Automobile/POV (up to 16 cubic meters)", "Automobile/POV (16 - 20 cubic meters)", "Automobile/POV (20 - 25 cubic meters)", "New Automobile", "New Automobile (up to 14 cubic meters)", "New Automobile (14 - 17 cubic meters)", "New Automobile (17 - 25 cubic meters)", "New Automobile (up to 16 cubic meters)", "New Automobile (16 - 20 cubic meters)", "New Automobile (20 - 25 cubic meters)", "Motorhome(s)", "Truck(s)", "Bus(es)", "Van(s)", "Chassis", "Travel trailer(s)", "Utility trailer(s)", "5th wheel trailer(s)", "Agriculture Equipment", "Construction Equipment", "Forestry Equipment", "Mining Equipment", "Handling Equipment", "Crane(s)", "Tractor(s)", "Boat(s) on Trailer", "Boat(s) on Cradle", "Static", "Static Machinery", "Special Purpose Vehicles", "Motorcycle(s)", "All-Terrain Vehicle(s)", "Jet Ski(s) (up to 2 cbm)" }));

        jLabel18.setText("$");

        jLabel64.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel64.setText("Commodity Description");

        jLabel57.setText("$");

        updateCommodityDescriptionTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel72.setText("$");

        jLabel65.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel65.setText("Handling Instructions");

        jLabel73.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel73.setText("%");

        updateHandlingInstructionsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Self-propelled", "Towable", "Static", "MAFI", "Forkliftable", "Static (MAFI)", "Static (Forkliftable)" }));

        jLabel66.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel66.setText("OFT");

        jLabel67.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel67.setText("BAF");

        jLabel68.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel68.setText("ECA");

        javax.swing.GroupLayout ViewQuotePanelLayout = new javax.swing.GroupLayout(ViewQuotePanel);
        ViewQuotePanel.setLayout(ViewQuotePanelLayout);
        ViewQuotePanelLayout.setHorizontalGroup(
            ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
            .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, ViewQuotePanelLayout.createSequentialGroup()
                            .addComponent(jLabel78)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(updateQuoteIDTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(updateQuoteIDSearchButton))
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5)
                        .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                            .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane12)
                                .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, ViewQuotePanelLayout.createSequentialGroup()
                            .addComponent(updateEditQuoteCustomerNameLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(updateEditQuoteCustomerNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editCustomerButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateEditQuoteCustomerNameLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(authorLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(authorLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(updateEditQuoteCustomerNameLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lastUpdatedByLabel))
                        .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                            .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel69)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel57)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateTHCTextField)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateThcComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateThcIncludedCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateThcAttachedCheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel70)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateWfgTextField)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateWfgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateWfgIncludedCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateWfgAttachedCheckBox))
                                .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel66)
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateOFTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateOftUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel67)
                                    .addGap(24, 24, 24)
                                    .addComponent(updateBAFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel73)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateBafIncludedCheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel68)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel72)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateEcaBafTextField)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateEcaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateEcaIncludedCheckBox))
                                .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                                    .addComponent(updateWarRiskCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel71)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateDocumentationFeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateDocFeeIncludedCheckBox)
                                    .addGap(4, 4, 4)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateContractRateCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateSpotRateCheckBox))
                                .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel64)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateCommodityDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(107, 107, 107))
                        .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                            .addComponent(updateBookedCheckBox)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(updateDeclineCheckBox)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(updateDeclineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(quoteFeedbackCheckBox)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(quoteFeedbackComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(quoteFeedbackTextField))
                        .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                            .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel63)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateCommodityClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel65)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateHandlingInstructionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateQuoteAccessoriesCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(updateQuoteMAFIMinimumCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updateEditMAFIMinimumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                                            .addComponent(jLabel124)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(currentAlphaNumeralLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(authorLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel129)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(updateAlphaNumeralTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                                            .addComponent(jLabel59)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(updateTradeLane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel60)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(updatePOLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel61)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(updatePODTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel62)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(updateTshp1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel76)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(updateTshp2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(94, 94, 94)))
                    .addContainerGap()))
        );

        ViewQuotePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {updateTshp1TextField, updateTshp2TextField});

        ViewQuotePanelLayout.setVerticalGroup(
            ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewQuotePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel21)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel78)
                        .addComponent(updateQuoteIDTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateQuoteIDSearchButton))
                    .addGap(5, 5, 5)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(updateEditQuoteCustomerNameLabel3)
                        .addComponent(updateEditQuoteCustomerNameLabel)
                        .addComponent(updateEditQuoteCustomerNameLabel1)
                        .addComponent(updateEditQuoteCustomerNameLabel2)
                        .addComponent(authorLabel1)
                        .addComponent(authorLabel)
                        .addComponent(lastUpdatedByLabel)
                        .addComponent(editCustomerButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel124)
                        .addComponent(currentAlphaNumeralLabel)
                        .addComponent(jLabel129)
                        .addComponent(updateAlphaNumeralTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(authorLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel60)
                        .addComponent(updatePOLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel61)
                        .addComponent(updatePODTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel62)
                        .addComponent(updateTshp1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel76)
                        .addComponent(updateTshp2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel59)
                        .addComponent(updateTradeLane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel63)
                        .addComponent(updateCommodityClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel65)
                        .addComponent(updateHandlingInstructionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateQuoteAccessoriesCheckBox)
                        .addComponent(updateQuoteMAFIMinimumCheckBox)
                        .addComponent(updateEditMAFIMinimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel64)
                        .addComponent(updateCommodityDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel66)
                        .addComponent(jLabel16)
                        .addComponent(updateOFTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateOftUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel67)
                        .addComponent(updateBAFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel73)
                        .addComponent(updateBafIncludedCheckBox)
                        .addComponent(jLabel68)
                        .addComponent(jLabel72)
                        .addComponent(updateEcaBafTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateEcaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateEcaIncludedCheckBox))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel69)
                        .addComponent(jLabel57)
                        .addComponent(updateTHCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateThcComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateThcIncludedCheckBox)
                        .addComponent(updateThcAttachedCheckBox)
                        .addComponent(jLabel70)
                        .addComponent(updateWfgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(updateWfgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateWfgIncludedCheckBox)
                        .addComponent(updateWfgAttachedCheckBox))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(updateWarRiskCheckBox)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel71)
                        .addComponent(updateDocumentationFeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateDocFeeIncludedCheckBox)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateContractRateCheckBox)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateSpotRateCheckBox))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(updateBookedCheckBox)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateDeclineCheckBox)
                        .addComponent(updateDeclineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quoteFeedbackCheckBox)
                        .addComponent(quoteFeedbackComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quoteFeedbackTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel54))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(ViewQuotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ViewQuotePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(ViewQuotePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerButtonActionPerformed
        // TODO add your handling code here:
        updateEditQuoteCustomerName ue = new updateEditQuoteCustomerName();
        ue.setVisible(true);
        ue.show();
    }//GEN-LAST:event_editCustomerButtonActionPerformed

    private void updateQuoteIDSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateQuoteIDSearchButtonActionPerformed

        Connection conn = new DBConnection().connect();

        //Get quoteID from search field
        String quoteID = updateQuoteIDTextArea.getText();

        //SQL to get quote based on ID
        String sql = "SELECT * FROM allquotes WHERE ID='" + quoteID + "';";

        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String customerName = rs.getString("customerName");
                String tradeLane = rs.getString("tradeLane");
                String pol = rs.getString("pol");
                String pod = rs.getString("pod");
                String tshp1 = rs.getString("tshp1");
                String tshp2 = rs.getString("tshp2");
                String commodityClass = rs.getString("comm_class");
                String commodityDescription = rs.getString("comm_description");
                String handlingInstructions = rs.getString("handling_instructions");
                String oft = rs.getString("rate");
                String oftUnit = rs.getString("rate_unit");
                String baf = rs.getString("baf");
                boolean bafIncluded = rs.getBoolean("bafIncluded");
                String eca = rs.getString("eca_baf");
                String ecaUnit = rs.getString("eca_unit");
                boolean ecaIncluded = rs.getBoolean("ecaIncluded");
                String thc = rs.getString("thc");
                String thcUnit = rs.getString("thc_unit");
                boolean thcIncluded = rs.getBoolean("thcIncluded");
                String wfg = rs.getString("wfg");
                String wfgUnit = rs.getString("wfg_unit");
                boolean wfgIncluded = rs.getBoolean("wfgIncluded");
                String documentationFee = rs.getString("doc_fee");
                boolean documentationFeeIncluded = rs.getBoolean("documentationFeeIncluded");
                boolean warRisk = rs.getBoolean("war_risk");
                boolean spotRate = rs.getBoolean("spot_rate");
                boolean booked = rs.getBoolean("booked");
                String comments = rs.getString("comments");
                boolean thcAttached = rs.getBoolean("thcAttached");
                boolean wfgAttached = rs.getBoolean("wfgAttached");
                String authorID = rs.getString("user_ID");
                String updaterID = rs.getString("updateUserID");
                String currentAlphaNumeral = rs.getString("alpha_numeral");
                boolean deny = rs.getBoolean("deny");
                boolean mafi = rs.getBoolean("mafiMinimum");
                String mafiCharge = rs.getString("mafiMinimumCharge");
                boolean contractRate = rs.getBoolean("contract_rate");
                String reason_for_decline = rs.getString("reason_for_decline");
                Boolean feedback = rs.getBoolean("feedback");
                String feedbackType = rs.getString("feedbackType");
                String feedbackDescription = rs.getString("feedbackDescription");

                String alphaNumeral = null;

                String table = "SELECT commodity, quantity, l, w, h, kgs, length_inches, width_inches, height_inches, cbm, lbs, ID FROM packingList WHERE quoteID='" + quoteID + "';";
                try {
                    PreparedStatement data = conn.prepareStatement(table);
                    ResultSet rs1 = data.executeQuery(table);

                    updateEditPackingListTable.setModel(DbUtils.resultSetToTableModel(rs1));
                    TableColumnModel tcm = MainMenu.updateEditPackingListTable.getColumnModel();
                    tcm.getColumn(0).setHeaderValue("Commodity");
                    tcm.getColumn(0).setMinWidth(150);
                    tcm.getColumn(1).setHeaderValue("Qty");
                    tcm.getColumn(1).setMinWidth(45);
                    tcm.getColumn(2).setHeaderValue("L(cm)");
                    tcm.getColumn(2).setMinWidth(45);
                    tcm.getColumn(3).setHeaderValue("W(cm)");
                    tcm.getColumn(3).setMinWidth(45);
                    tcm.getColumn(4).setHeaderValue("H(cm)");
                    tcm.getColumn(4).setMinWidth(45);
                    tcm.getColumn(5).setHeaderValue("Kgs");
                    tcm.getColumn(5).setMinWidth(45);
                    tcm.getColumn(6).setHeaderValue("L(in)");
                    tcm.getColumn(6).setMinWidth(45);
                    tcm.getColumn(7).setHeaderValue("W(in)");
                    tcm.getColumn(7).setMinWidth(45);
                    tcm.getColumn(8).setHeaderValue("H(in)");
                    tcm.getColumn(8).setMinWidth(45);
                    tcm.getColumn(9).setHeaderValue("CBM");
                    tcm.getColumn(9).setMinWidth(45);
                    tcm.getColumn(10).setHeaderValue("LBs");
                    tcm.getColumn(10).setMinWidth(45);
                    tcm.getColumn(11).setMaxWidth(-9999);
                    tcm.getColumn(11).setMinWidth(-9999);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
                }

                //Get current alph-numeral from DB and display or display N/A if none exists
                if (currentAlphaNumeral == null || currentAlphaNumeral.equals("")) {
                    currentAlphaNumeralLabel.setText("N/A");
                } else if (!currentAlphaNumeral.equals("")) {
                    currentAlphaNumeralLabel.setText(currentAlphaNumeral);
                    //alphaNumeral = currentAlphaNumeral;
                }

                String current = currentAlphaNumeralLabel.getText();

                if (current.equals("") || current.equals("N/A")) {
                    updateAlphaNumeralTextField.setText("A");
                } else if (!current.equals("") || current.equals("N/A")) {
                    int charValue = current.charAt(0);
                    String next = String.valueOf((char) (charValue + 1));
                    updateAlphaNumeralTextField.setText(next);
                }

                if (ecaIncluded == true) {
                    eca = "";
                    ecaUnit = "N/A";
                }
                if (thcIncluded == true) {
                    thc = "";
                    thcUnit = "N/A";
                }
                if (wfgIncluded == true) {
                    wfg = "";
                    wfgUnit = "N/A";
                }
                if (documentationFeeIncluded == true) {
                    documentationFee = "N/A";
                }

                //Returns the value of the author and displays on authorLabel
                String sqlAuthor = "SELECT * FROM authorized_users WHERE userID ='" + authorID + "';";
                PreparedStatement ps2 = conn.prepareStatement(sqlAuthor);
                ResultSet rs2 = ps2.executeQuery();
                while (rs2.next()) {
                    String authorFN = rs2.getString("firstName");
                    String authorLN = rs2.getString("lastName");
                    String author = authorLN + ", " + authorFN;
                    authorLabel.setText(author);
                }

                //Returns the value of the updater and displays on updatedby label
                String updateAuthor = "SELECT * FROM authorized_users WHERE userID='" + updaterID + "';";
                PreparedStatement ps3 = conn.prepareStatement(updateAuthor);
                ResultSet rs3 = ps3.executeQuery();
                while (rs3.next()) {
                    String updaterFN = rs3.getString("firstName");
                    String updaterLN = rs3.getString("lastName");
                    String updater = updaterLN + ", " + updaterFN;
                    lastUpdatedByLabel.setText(updater);
                }

                updateEditQuoteCustomerNameLabel.setText(customerName);
                //currentAlphaNumeralLabel.setText(alphaNumeral);
                updateTradeLane.setSelectedItem(tradeLane);
                updatePOLTextField.setText(pol);
                updatePODTextField.setText(pod);
                updateTshp1TextField.setText(tshp1);
                updateTshp2TextField.setText(tshp2);
                updateCommodityClassComboBox.setSelectedItem(commodityClass);
                updateCommodityDescriptionTextField.setText(commodityDescription);
                updateHandlingInstructionsComboBox.setSelectedItem(handlingInstructions);
                updateOFTTextField.setText(oft);
                updateOftUnitComboBox.setSelectedItem(oftUnit);
                updateBAFTextField.setText(baf);
                updateBafIncludedCheckBox.setSelected(bafIncluded);
                updateEcaBafTextField.setText(eca);
                updateEcaComboBox.setSelectedItem(ecaUnit);
                updateEcaIncludedCheckBox.setSelected(ecaIncluded);
                updateTHCTextField.setText(thc);
                updateThcComboBox.setSelectedItem(thcUnit);
                updateThcIncludedCheckBox.setSelected(thcIncluded);
                updateThcAttachedCheckBox.setSelected(thcAttached);
                updateWfgTextField.setText(wfg);
                updateWfgComboBox.setSelectedItem(wfgUnit);
                updateWfgIncludedCheckBox.setSelected(wfgIncluded);
                updateWfgAttachedCheckBox.setSelected(wfgAttached);
                updateDocumentationFeeComboBox.setSelectedItem(documentationFee);
                updateDocFeeIncludedCheckBox.setSelected(documentationFeeIncluded);
                updateWarRiskCheckBox.setSelected(warRisk);
                updateSpotRateCheckBox.setSelected(spotRate);
                updateBookedCheckBox.setSelected(booked);
                updateCommentsTextArea.setText(comments);
                updateDeclineCheckBox.setSelected(deny);
                updateQuoteMAFIMinimumCheckBox.setSelected(mafi);
                updateEditMAFIMinimumTextField.setText(mafiCharge);
                updateContractRateCheckBox.setSelected(contractRate);
                updateDeclineComboBox.setSelectedItem(reason_for_decline);
                quoteFeedbackCheckBox.setSelected(feedback);
                quoteFeedbackComboBox.setSelectedItem(feedbackType);
                quoteFeedbackTextField.setText(feedbackDescription);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_updateQuoteIDSearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewQuote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewQuote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewQuote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewQuote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewQuote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewQuotePanel;
    public static javax.swing.JLabel authorLabel;
    private javax.swing.JLabel authorLabel1;
    private javax.swing.JLabel authorLabel2;
    public static javax.swing.JLabel currentAlphaNumeralLabel;
    private javax.swing.JButton editCustomerButton;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator9;
    public static javax.swing.JLabel lastUpdatedByLabel;
    private javax.swing.JCheckBox quoteFeedbackCheckBox;
    private javax.swing.JComboBox quoteFeedbackComboBox;
    private javax.swing.JTextField quoteFeedbackTextField;
    public static javax.swing.JTextField updateAlphaNumeralTextField;
    public static javax.swing.JTextField updateBAFTextField;
    public static javax.swing.JCheckBox updateBafIncludedCheckBox;
    public static javax.swing.JCheckBox updateBookedCheckBox;
    public static javax.swing.JTextArea updateCommentsTextArea;
    public static javax.swing.JComboBox updateCommodityClassComboBox;
    public static javax.swing.JTextField updateCommodityDescriptionTextField;
    public static javax.swing.JCheckBox updateContractRateCheckBox;
    public static javax.swing.JCheckBox updateDeclineCheckBox;
    public static javax.swing.JComboBox updateDeclineComboBox;
    public static javax.swing.JCheckBox updateDocFeeIncludedCheckBox;
    public static javax.swing.JComboBox updateDocumentationFeeComboBox;
    public static javax.swing.JTextField updateEcaBafTextField;
    public static javax.swing.JComboBox updateEcaComboBox;
    public static javax.swing.JCheckBox updateEcaIncludedCheckBox;
    public static javax.swing.JTextField updateEditMAFIMinimumTextField;
    public static javax.swing.JTable updateEditPackingListTable;
    public static javax.swing.JLabel updateEditQuoteCustomerNameLabel;
    private javax.swing.JLabel updateEditQuoteCustomerNameLabel1;
    private javax.swing.JLabel updateEditQuoteCustomerNameLabel2;
    public static javax.swing.JLabel updateEditQuoteCustomerNameLabel3;
    public static javax.swing.JComboBox updateHandlingInstructionsComboBox;
    public static javax.swing.JTextField updateOFTTextField;
    public static javax.swing.JComboBox updateOftUnitComboBox;
    public static javax.swing.JTextField updatePODTextField;
    public static javax.swing.JTextField updatePOLTextField;
    public static javax.swing.JCheckBox updateQuoteAccessoriesCheckBox;
    private javax.swing.JButton updateQuoteIDSearchButton;
    public static javax.swing.JTextField updateQuoteIDTextArea;
    public static javax.swing.JCheckBox updateQuoteMAFIMinimumCheckBox;
    public static javax.swing.JCheckBox updateSpotRateCheckBox;
    public static javax.swing.JTextField updateTHCTextField;
    public static javax.swing.JCheckBox updateThcAttachedCheckBox;
    public static javax.swing.JComboBox updateThcComboBox;
    public static javax.swing.JCheckBox updateThcIncludedCheckBox;
    public static javax.swing.JComboBox updateTradeLane;
    public static javax.swing.JTextField updateTshp1TextField;
    public static javax.swing.JTextField updateTshp2TextField;
    public static javax.swing.JCheckBox updateWarRiskCheckBox;
    public static javax.swing.JCheckBox updateWfgAttachedCheckBox;
    public static javax.swing.JComboBox updateWfgComboBox;
    public static javax.swing.JCheckBox updateWfgIncludedCheckBox;
    public static javax.swing.JTextField updateWfgTextField;
    // End of variables declaration//GEN-END:variables
}
