package RORO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cmeehan
 */
import Connections.DBConnection;
import javax.swing.*;
import java.awt.*;
import java.sql.*;

public class existingCustomer extends javax.swing.JDialog {

    public existingCustomer() {
        initComponents();
        setIcon();

    }

    protected int tf;

    public existingCustomer(int tf) {
        this.tf = tf;
    }

    /**
     * Creates new form logIn
     *
     * @param parent
     * @param modal
     */
    public existingCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(this);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        existingCustomerTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cancelCustomerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log-In \"K\" Line RORO Quoting");
        setIconImage(null);
        setIconImages(null);

        existingCustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "1", "Company Name", "Contact Name", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(existingCustomerTable);

        jLabel1.setText("Customers");

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cancelCustomerButton.setText("Cancel");
        cancelCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelCustomerButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cancelCustomerButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Connection conn = new DBConnection().connect();

        int selectedRowIndex = existingCustomerTable.getSelectedRow();
        Object selectedRowID = existingCustomerTable.getValueAt(selectedRowIndex, 0);
        //String firstname = "";
        System.out.println(selectedRowID);
        String sql = "SELECT * FROM rorocustomers WHERE ID=" + selectedRowID + ";";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery(sql);

            if (rs.next()) {
                this.dispose();

                String firstname = rs.getString("firstname");
                String lastname = rs.getString("lastname");
                String officephone = rs.getString("officephone");
                String mobilephone = rs.getString("mobilephone");
                String email = rs.getString("email");
                String title = rs.getString("title");
                String contact_office_address = rs.getString("contact_office_address");
                String contact_office_address2 = rs.getString("contact_office_address2");
                String contact_office_city = rs.getString("contact_office_city");
                String contact_office_state = rs.getString("contact_office_state");
                String contact_office_zip = rs.getString("contact_office_zip_code");
                String contact_office_country = rs.getString("contact_office_country");
                String company = rs.getString("company");
                String dba = rs.getString("dba");
                String oti = rs.getString("oti");
                Boolean freight_forwarder = rs.getBoolean("freight_forwarder");
                Boolean NVOCC = rs.getBoolean("NVOCC");
                Boolean BCO = rs.getBoolean("BCO");
                Boolean Other = rs.getBoolean("Other");
                String mainphone = rs.getString("mainphone");
                String secondaryphone = rs.getString("secondaryphone");
                String fax = rs.getString("fax");
                String mainemail = rs.getString("mainemail");
                String address1 = rs.getString("address1");
                String address2 = rs.getString("address2");
                String city = rs.getString("city");
                String state = rs.getString("state");
                String zip = rs.getString("zip");
                String country = rs.getString("country");
                Boolean contract = rs.getBoolean("contract");
                String contractnumber = rs.getString("contractnumber");
                String comments = rs.getString("comments");
                String contractExpirationDate = rs.getString("contractExpiration");
                String ID = selectedRowID.toString();

                MainMenu.existingCompanyFirstNameTextField.setText(firstname);
                MainMenu.existingCompanyLastNameTextField.setText(lastname);
                MainMenu.existingCompanyOfficePhoneTextField.setText(officephone);
                MainMenu.existingCompanyMobilePhoneTextField.setText(mobilephone);
                MainMenu.existingCompanyEmailTextField.setText(email);
                MainMenu.existingCompanyTitleTextField.setText(title);
                MainMenu.updatePCAddressTextfield.setText(contact_office_address);
                MainMenu.updatePCSuiteTextField.setText(contact_office_address2);
                MainMenu.updatePCCityTextField.setText(contact_office_city);
                MainMenu.updatePCStateTextField.setText(contact_office_state);
                MainMenu.updatePCZipTextField.setText(contact_office_zip);
                MainMenu.updatePCCountryTextField.setText(contact_office_country);
                MainMenu.existingCompanyCompanyTextField.setText(company);
                MainMenu.existingCompanyDBATextField.setText(dba);
                MainMenu.existingCompanyOTINumberTextField.setText(oti);
                MainMenu.existingCustomerFreightForwarderRadioButton.setSelected(freight_forwarder);
                MainMenu.existingCustomerNVOCCRadioButton.setSelected(NVOCC);
                MainMenu.existingCustomerBCORadioButton.setSelected(BCO);
                MainMenu.existingCustomerOtherRadioButton.setSelected(Other);
                MainMenu.existingCompanyMainPhoneTextField.setText(mainphone);
                MainMenu.existingCompanySecondaryPhoneTextField.setText(secondaryphone);
                MainMenu.existingCompanyFaxNumberTextField.setText(fax);
                MainMenu.existingCompanyMainEmailTextField.setText(mainemail);
                MainMenu.existingCompanyAddress1TextField.setText(address1);
                MainMenu.existingCompanyAddress2TextField.setText(address2);
                MainMenu.existingCompanyCityTextField.setText(city);
                MainMenu.existingCompanyStateTextField.setText(state);
                MainMenu.existingCompanyZipTextField.setText(zip);
                MainMenu.existingCompanyCountryTextField.setText(country);
                MainMenu.existingCompanyContractNumberTextField.setText(contractnumber);
                MainMenu.existingCustomerContractExpirationDatePicker.getJFormattedTextField().setText(contractExpirationDate);
                MainMenu.existingCompanyCommentsTextArea.setText(comments);
                MainMenu.existingCompanyIDTextField.setText(ID);
                MainMenu.existingCompanyNameTextField.setText(company);

                System.out.println(firstname);

                String corrTableSql = "SELECT ID, firstname, date , subject FROM customer_correspondence WHERE customerID=" + selectedRowID + ";";

                try {
                    PreparedStatement ct = conn.prepareStatement(corrTableSql);
                    ResultSet corrTable = ct.executeQuery(corrTableSql);

                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

            }
            System.out.println(ps);
        } catch (SQLException | HeadlessException e) {
            System.out.println(e.getMessage());
        }
        //MainMenu.existingCompanyFirstNameTextField.setText("Hello");

        System.out.println(selectedRowID);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCustomerButtonActionPerformed
        // TODO add your handling code here:

        MainMenu.existingCompanyIDTextField.setText("");
        MainMenu.existingCompanyNameTextField.setText("");
        this.dispose();
    }//GEN-LAST:event_cancelCustomerButtonActionPerformed

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(existingCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            existingCustomer dialog = new existingCustomer(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelCustomerButton;
    public static javax.swing.JTable existingCustomerTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
