package RORO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cmeehan
 */
import UserAccess.passwordReset;
import Connections.DBConnection;
import javax.swing.*;
import java.awt.*;
import java.sql.*;

public class forgotUsernamePassword extends javax.swing.JDialog {

    
    public Connection connection(){
        Connection conn = new DBConnection().connect();
        return conn;
    }
    
    public forgotUsernamePassword() {
        initComponents();
        setIcon();

    }

    
    /**
     * Creates new form forgotUsernamePassword
     *
     * @param parent
     * @param modal
     */
    public forgotUsernamePassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        submitUsernameorEmail = new javax.swing.JButton();
        securityQuestionLabel = new javax.swing.JLabel();
        answerTextField = new javax.swing.JTextField();
        securityQuestionLabel2 = new javax.swing.JLabel();
        submitAnswerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log-In \"K\" Line RORO Quoting");
        setIconImage(null);
        setIconImages(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forgot Username/Password");

        jLabel2.setText("Username");

        usernameTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        emailTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel3.setText("Email:");

        submitUsernameorEmail.setText("Submit");
        submitUsernameorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUsernameorEmailActionPerformed(evt);
            }
        });

        securityQuestionLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        securityQuestionLabel.setText("Security Question: ");

        answerTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        securityQuestionLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        securityQuestionLabel2.setText("Answer:");

        submitAnswerButton.setText("Submit");
        submitAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAnswerButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("OR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(submitUsernameorEmail)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(securityQuestionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(securityQuestionLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(answerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(submitAnswerButton))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitUsernameorEmail)
                .addGap(13, 13, 13)
                .addComponent(securityQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(securityQuestionLabel2)
                    .addComponent(answerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitAnswerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitUsernameorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUsernameorEmailActionPerformed
        //Submit username or Email
        
        String username = usernameTextField.getText();
        String email = emailTextField.getText();
        
        Connection conn = new DBConnection().connect();
        
        String SQL = null;
        
        if(username.equals("") && !email.equals("")){
            SQL = "SELECT * FROM authorized_users WHERE email='"+email+"';";
        }else if(!username.equals("") && email.equals("")){
            SQL = "SELECT * FROM authorized_users WHERE username='"+username+"';";
        }else if(!username.equals("") && !email.equals("")){
            SQL = "SELECT * FROM authorized_users WHERE username='"+username+"' AND email='"+email+"';";
        }else{
            JOptionPane.showMessageDialog(null,"You must enter either your username or email for the account. If you do not know either of these, please contact your system administrator at connor.meehan@us.kline.com");
        }
        
        try{
            PreparedStatement ps = conn.prepareStatement(SQL);
            ResultSet rs = ps.executeQuery(SQL);
            if(rs.next()){
                String securityQuetion = rs.getString("security_question");
                securityQuestionLabel.setText(securityQuetion);
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid user input. Please try again");
                usernameTextField.setText("");
                emailTextField.setText("");
            }
        }catch(Exception e){
            String error = "Error: "+e.getMessage();
            JOptionPane.showMessageDialog(null, error);
        }
        
    }//GEN-LAST:event_submitUsernameorEmailActionPerformed

    private void submitAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAnswerButtonActionPerformed
        //Check security question answer and redirct to passwordReset if true
        String securityAnswer = answerTextField.getText().toLowerCase();
        String username = usernameTextField.getText();
        String email = emailTextField.getText();
        String SQL = null;
        
        Connection conn = new DBConnection().connect();
        
        if(username.equals("")&& !email.equals("")){
            SQL = "SELECT * FROM authorized_users WHERE email='"+email+";";
        }else if(!username.equals("")&& email.equals("")){
            SQL = "SELECT * FROM authorized_users WHERE username='"+username+"';";
        }
        
        try{
            PreparedStatement ps = conn.prepareStatement(SQL);
            ResultSet rs = ps.executeQuery(SQL);
            if(rs.next()){
                String correctAnswer = rs.getString("answer");
                String userName = rs.getString("username");
                
                if(securityAnswer.equals(correctAnswer)){
                    passwordReset pr = new passwordReset();
                    pr.setVisible(true);
                    pr.show();
                    this.dispose();
                    pr.usernameLabel.setText(userName);
                }else{
                    JOptionPane.showMessageDialog(null, "Sorry, that is not correct, please try again.\n If you cannot remember the correct answer, please contact your systems administrator.");
                    answerTextField.setText("");
                }
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_submitAnswerButtonActionPerformed

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotUsernamePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            forgotUsernamePassword dialog = new forgotUsernamePassword(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField answerTextField;
    public static javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel securityQuestionLabel;
    public static javax.swing.JLabel securityQuestionLabel2;
    private javax.swing.JButton submitAnswerButton;
    private javax.swing.JButton submitUsernameorEmail;
    public static javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

}
