package Administrator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cmeehan
 */
import Connections.DBConnection;
import Administrator.AdministratorMenu;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

public class addNewUser extends javax.swing.JDialog {

    public addNewUser() {
        initComponents();
        setIcon();

    }

    /**
     * Creates new form forgotUsernamePassword
     *
     * @param parent
     * @param modal
     */
    public addNewUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(this);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        accessLevelComboBox = new javax.swing.JComboBox();
        accessLevelLabel = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        departmentComboBox = new javax.swing.JComboBox();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log-In \"K\" Line RORO Quoting");
        setIconImage(null);
        setIconImages(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New User");

        firstNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        firstNameLabel.setText("First Name:");

        lastNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lastNameLabel.setText("Last Name:");

        usernameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usernameLabel.setText("Username:");

        firstNameTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lastNameTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        usernameTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("**Username must match desktop username**");

        jButton3.setText("Auto-assign");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        accessLevelComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        accessLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Administrative", "General", "Limited", "None" }));

        accessLevelLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        accessLevelLabel.setText("Access Level:");

        departmentLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        departmentLabel.setText("Department:");

        departmentComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "Administration", "Sales", "Trade Management", "Customer Service" }));

        emailLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        emailLabel.setText("Email:");

        emailTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(accessLevelLabel)
                            .addComponent(departmentLabel)
                            .addComponent(emailLabel)
                            .addComponent(usernameLabel))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accessLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel15)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {firstNameTextField, lastNameTextField, usernameTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessLevelLabel)
                    .addComponent(accessLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentLabel)
                    .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Grant new user access to software   
        //Establish connection with database
        Connection conn = new DBConnection().connect();
        String firstName = firstNameTextField.getText();
        String lastName = lastNameTextField.getText();
        String rights = accessLevelComboBox.getSelectedItem().toString();
        String department = departmentComboBox.getSelectedItem().toString();
        String email = emailTextField.getText();
        String username = usernameTextField.getText();
        if (firstName.equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter the new user's first name");
            firstNameLabel.setText("First Name:*");
            float[] hsb = Color.RGBtoHSB(255, 0, 0, null);
            float hue = hsb[0];
            float saturation = hsb[1];
            float brightness = hsb[2];
            firstNameLabel.setForeground(Color.getHSBColor(hue, saturation, brightness));
        }
        if (lastName.equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter the new user's first name");
            lastNameLabel.setText("Last Name:*");
            float[] hsb = Color.RGBtoHSB(255, 0, 0, null);
            float hue = hsb[0];
            float saturation = hsb[1];
            float brightness = hsb[2];
            lastNameLabel.setForeground(Color.getHSBColor(hue, saturation, brightness));
        }
        if (rights.equals("N/A")) {
            JOptionPane.showMessageDialog(null, "You must enter the new user's first name");
            accessLevelLabel.setText("Access Level:*");
            float[] hsb = Color.RGBtoHSB(255, 0, 0, null);
            float hue = hsb[0];
            float saturation = hsb[1];
            float brightness = hsb[2];
            accessLevelLabel.setForeground(Color.getHSBColor(hue, saturation, brightness));
        }
        if (department.equals("N/A")) {
            JOptionPane.showMessageDialog(null, "You must enter the new user's first name");
            departmentLabel.setText("Department:*");
            float[] hsb = Color.RGBtoHSB(255, 0, 0, null);
            float hue = hsb[0];
            float saturation = hsb[1];
            float brightness = hsb[2];
            departmentLabel.setForeground(Color.getHSBColor(hue, saturation, brightness));
        }
        if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter the new user's first name");
            emailLabel.setText("Email:*");
            float[] hsb = Color.RGBtoHSB(255, 0, 0, null);
            float hue = hsb[0];
            float saturation = hsb[1];
            float brightness = hsb[2];
            emailLabel.setForeground(Color.getHSBColor(hue, saturation, brightness));
        }
        if (username.equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter the new user's first name");
            usernameLabel.setText("Username:*");
            float[] hsb = Color.RGBtoHSB(255, 0, 0, null);
            float hue = hsb[0];
            float saturation = hsb[1];
            float brightness = hsb[2];
            usernameLabel.setForeground(Color.getHSBColor(hue, saturation, brightness));
        }
        String addUser = "INSERT INTO authorized_users (firstName, lastname, rights, department, username, email, password) VALUES (?,?,?,?,?,?,?);";

        try {
            PreparedStatement psAddUser = conn.prepareStatement(addUser);
            psAddUser.setString(1,firstName);
            psAddUser.setString(2, lastName);
            psAddUser.setString(3, rights);
            psAddUser.setString(4, department);
            psAddUser.setString(5, username);
            psAddUser.setString(6, email);
            psAddUser.setString(7, "password");
            int rsAddUser = psAddUser.executeUpdate();
            JOptionPane.showMessageDialog(null, "New user has been added to the database");
            this.dispose();
            
            String sql = "SELECT userID, lastName, firstName, username, password, department, rights, email, title FROM authorized_users";

        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery(sql);
            AdministratorMenu.CurrentUsersTable.setModel(DbUtils.resultSetToTableModel(rs));
            TableColumnModel tcm = AdministratorMenu.CurrentUsersTable.getColumnModel();
            tcm.getColumn(0).setHeaderValue("ID");
            tcm.getColumn(1).setHeaderValue("Last Name");
            tcm.getColumn(2).setHeaderValue("First Name");
            tcm.getColumn(3).setHeaderValue("Username");
            tcm.getColumn(4).setHeaderValue("Password");
            tcm.getColumn(5).setHeaderValue("Department");
            tcm.getColumn(6).setHeaderValue("Rights");
            tcm.getColumn(7).setHeaderValue("Email");
            tcm.getColumn(8).setHeaderValue("Title");

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
            
        } catch (SQLException | HeadlessException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String firstName = firstNameTextField.getText().toLowerCase();
        String lastName = lastNameTextField.getText().toLowerCase();
        String username = firstName.substring(0, 1) + lastName;
        usernameTextField.setText(username);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            addNewUser dialog = new addNewUser(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accessLevelComboBox;
    private javax.swing.JLabel accessLevelLabel;
    private javax.swing.JComboBox departmentComboBox;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

}
